name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  GITHUB_TOKEN:
    description: "Github token"
    required: true
    default: "0"
  ORGANIZATION:
    description: "Organization name"
    required: true
    default: "TestingOrganizationForAutomation"
  PROJECT_NUMBER:
    description: "Number of the project"
    required: true
    default: "1"
  PR_ID:
    description: "ID of pull request"
    required: true
    default: "1"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "index.js"
